views:
  - type: masonry
    path: ''
    cards:
      - type: horizontal-stack
        cards:
          - graph: line
            type: sensor
            entity: sensor.shi_du
            detail: 2
            icon: mdi:thermometer
            unit: ℃
            hours_to_show: 24
          - graph: line
            type: sensor
            entity: sensor.wen_du
            detail: 1
            icon: mdi:thermometer-water
            unit: '%'
            hours_to_show: 24
      - type: entities
        entities:
          - entity: light.ke_ting_zhu_deng
          - entity: light.ke_ting_deng_dai_deng
          - entity: light.ke_ting_tong_deng
          - entity: button.da_kai_ke_ting_sha_lian
          - entity: button.guan_bi_ke_ting_sha_lian
          - entity: climate.ke_ting_kong_diao
            secondary_info: state
        show_header_toggle: true
        title: 客厅
      - type: entities
        entities:
          - entity: button.xuan_guan_an_jian
          - entity: button.chi_jia_mo_shi
          - entity: light.can_ting_zhu_deng
          - entity: light.can_ting_tong_deng
          - entity: light.xuan_guan_deng_dai
          - entity: light.xuan_guan_tong_deng
          - entity: climate.can_ting_kong_diao
            secondary_info: state
        title: 玄关和餐厅
        state_color: false
      - type: entities
        entities:
          - entity: light.zhu_wo_zhu_deng
          - entity: light.zhu_wo_tong_deng
          - entity: light.zhu_wo_deng_dai_deng
          - entity: button.da_kai_zhu_wo_bu_lian
          - entity: button.guan_bi_zhu_wo_bu_lian
          - entity: button.da_kai_zhu_wo_sha_lian
          - entity: button.guan_bi_zhu_wo_sha_lian
          - entity: light.zhu_wei_tong_deng
          - entity: light.zhu_wei_deng_dai_deng
          - entity: climate.zhu_wo_kong_diao
            secondary_info: state
        show_header_toggle: true
        title: 主卧
      - type: entities
        entities:
          - entity: light.ci_wo_zhu_deng
          - entity: light.ci_wo_deng_dai_deng
          - entity: light.ci_wo_tong_deng
          - entity: button.da_kai_ci_wo_bu_lian
          - entity: button.da_kai_ci_wo_sha_lian
          - entity: button.guan_bi_ci_wo_bu_lian
          - entity: button.guan_bi_ci_wo_sha_lian
          - entity: climate.ci_wo_kong_diao
            secondary_info: state
        show_header_toggle: true
        title: 次卧
      - type: entities
        entities:
          - entity: climate.er_tong_fang_kong_diao
            secondary_info: state
          - entity: climate.shu_fang_kong_diao
            secondary_info: state
        show_header_toggle: true
        title: 儿童房和书房
    title: 房间
  - type: masonry
    title: 空调
    path: unknown
    cards:
      - type: horizontal-stack
        cards:
          - type: thermostat
            entity: climate.ke_ting_kong_diao
            features:
              - type: climate-hvac-modes
              - style: icons
                type: climate-fan-modes
                fan_modes:
                  - auto
                  - '1'
                  - '3'
                  - '5'
          - type: thermostat
            entity: climate.can_ting_kong_diao
            features:
              - type: climate-hvac-modes
              - style: icons
                type: climate-fan-modes
                fan_modes:
                  - auto
                  - '1'
                  - '3'
                  - '5'
      - type: horizontal-stack
        cards:
          - type: thermostat
            entity: climate.zhu_wo_kong_diao
            features:
              - type: climate-hvac-modes
              - style: icons
                type: climate-fan-modes
                fan_modes:
                  - auto
                  - '1'
                  - '3'
                  - '5'
          - type: thermostat
            entity: climate.ci_wo_kong_diao
            features:
              - type: climate-hvac-modes
              - style: icons
                type: climate-fan-modes
                fan_modes:
                  - auto
                  - '1'
                  - '3'
                  - '5'
      - type: horizontal-stack
        cards:
          - type: thermostat
            entity: climate.er_tong_fang_kong_diao
            features:
              - type: climate-hvac-modes
              - style: icons
                type: climate-fan-modes
                fan_modes:
                  - auto
                  - '1'
                  - '3'
                  - '5'
          - type: thermostat
            entity: climate.shu_fang_kong_diao
            features:
              - type: climate-hvac-modes
              - style: icons
                type: climate-fan-modes
                fan_modes:
                  - auto
                  - '1'
                  - '3'
                  - '5'
