###################################################################
# 版权所有 2023 尊贵的幸福里业主
#  适用于南98C户型，A6/A7栋
# 
# 使用方法
#  HA中添加集成KNX
#  configuration.yaml中添加 knx: !include <本文件名字>
#  重启HA

light:
    - name: "总控灯3"  # 非智能灯都接在这里，如果不想让语音控制误触发，可以注释掉
      address: "1/0/40"
      state_address: "1/0/40"
    - name: "总控灯2" # 悬空未使用
      address: "1/0/39"
      state_address: "1/0/39"
    - name: "总控灯1" # 悬空未使用
      address: "1/0/38"
      state_address: "1/0/38"
    - name: "主卫筒灯"
      address: "1/0/37"
      state_address: "1/0/37"
    - name: "主卫灯带灯"
      address: "1/0/36"
      state_address: "1/0/36"
    - name: "主卧衣柜灯"
      address: "1/0/35"
      state_address: "1/0/35"
    - name: "主卧筒灯"
      address: "1/0/34"
      state_address: "1/0/34"
    - name: "主卧灯带灯"
      address: "1/0/33"
      state_address: "1/0/33"
    - name: "主卧主灯"
      address: "1/0/24"
      state_address: "1/0/24"
    - name: "客厅主灯"
      address: "1/0/23"
      state_address: "1/0/23"
    - name: "客厅灯带灯"
      address: "1/0/22"
      state_address: "1/0/22"
    - name: "客厅筒灯"
      address: "1/0/21"
      state_address: "1/0/21"
    - name: "餐厅主灯"
      address: "1/0/20"
      state_address: "1/0/20"
    - name: "餐厅筒灯"
      address: "1/0/19"
      state_address: "1/0/19"
    - name: "玄关灯带"
      address: "1/0/18"
      state_address: "1/0/18"
    - name: "玄关筒灯"
      address: "1/0/17"
      state_address: "1/0/17"

fan:
    - name: "新风风速"
      address: "14/3/1"
      state_address: "14/3/1"
      max_step: 3


switch:
    - name: "新风开关"
      address: "14/1/1"
      state_address: "14/1/1"


# 传感器的数据来源于新风
# 实际测试表明传感器会频繁推送数据，占用大量带宽
#
#    - name: "二氧化碳"
#      state_address: "6/2/81"
#      type: 2byte_float
#      sync_state: init
#    - name: "TVOC"
#      state_address: "6/3/81"
#      type: 2byte_float
#      sync_state: true
#    - name: "PM2.5"
#      state_address: "6/1/81"
#      type: 2byte_float
#      sync_state: true
      
sensor:
    - name: "湿度"
      state_address: "6/6/81"
      type: 2byte_float
      sync_state: true
    - name: "温度"
      state_address: "6/5/81"
      type: 2byte_float
      sync_state: true


select:
    - name: "客厅布帘"
      address: "2/0/65"
      payload_length: 1
      options:
        - option: "开"
          payload: 1
        - option: "合"
          payload: 2
        - option: "停"
          payload: 0
    - name: "客厅纱帘"
      address: "2/0/66"
      payload_length: 1
      options:
        - option: "开"
          payload: 1
        - option: "合"
          payload: 2
        - option: "停"
          payload: 0
    - name: "主卧布帘"
      address: "2/0/67"
      payload_length: 1
      options:
        - option: "开"
          payload: 1
        - option: "合"
          payload: 2
        - option: "停"
          payload: 0
    - name: "主卧纱帘"
      address: "2/0/68"
      payload_length: 1
      options:
        - option: "开"
          payload: 1
        - option: "合"
          payload: 2
        - option: "停"
          payload: 0
    - name: "次卧空调风速"
      address: "12/3/1"
      state_address: "12/3/129"
      payload_length: 1
      options:
        - option: "自动"
          payload: 0
        - option: "低"
          payload: 1
        - option: "中"
          payload: 3
        - option: "高"
          payload: 5
    - name: "书房空调风速"
      address: "12/3/2"
      state_address: "12/3/130"
      payload_length: 1
      options:
        - option: "自动"
          payload: 0
        - option: "低"
          payload: 1
        - option: "中"
          payload: 3
        - option: "高"
          payload: 5
    - name: "客厅空调风速"
      address: "12/3/3"
      state_address: "12/3/131"
      payload_length: 1
      options:
        - option: "自动"
          payload: 0
        - option: "低"
          payload: 1
        - option: "中"
          payload: 3
        - option: "高"
          payload: 5
    - name: "主卧空调风速"
      address: "12/3/4"
      state_address: "12/3/132"
      payload_length: 1
      options:
        - option: "自动"
          payload: 0
        - option: "低"
          payload: 1
        - option: "中"
          payload: 3
        - option: "高"
          payload: 5

#按键不知道怎么用

button:
    - name: "玄关按键"
      address: "0/0/17"
    - name: "主卧按键"
      address: "0/0/18"

# 开发商的空调的风速控制不是KNX标准的，因此挪到select实体

climate:
    - name: "次卧空调"
      temperature_address: "12/5/129"
      target_temperature_address: "12/4/1"
      target_temperature_state_address: "12/4/129"
      on_off_address: "12/1/1"
      on_off_state_address: "12/1/129"
      controller_mode_address: "12/2/1"
      controller_mode_state_address: "12/2/129"
    - name: "书房空调"
      temperature_address: "12/5/130"
      target_temperature_address: "12/4/2"
      target_temperature_state_address: "12/4/130"
      on_off_address: "12/1/2"
      on_off_state_address: "12/1/130"
      controller_mode_address: "12/2/2"
      controller_mode_state_address: "12/2/130"
    - name: "客厅空调"
      temperature_address: "12/5/131"
      target_temperature_address: "12/4/3"
      target_temperature_state_address: "12/4/131"
      on_off_address: "12/1/3"
      on_off_state_address: "12/1/131"
      controller_mode_address: "12/2/3"
      controller_mode_state_address: "12/2/131"
    - name: "主卧空调"
      temperature_address: "12/5/132"
      target_temperature_address: "12/4/4"
      target_temperature_state_address: "12/4/132"
      on_off_address: "12/1/4"
      on_off_state_address: "12/1/132"
      controller_mode_address: "12/2/4"
      controller_mode_state_address: "12/2/132"
  