###################################################################
# 版权所有 2023 尊贵的幸福里业主
#  适用于南A145不知道哪个户型
#
# 使用方法
#  HA中添加集成KNX
#  configuration.yaml中添加 knx: !include <本文件名字>
#  重启HA

light:
    - name: "主卫筒灯"
      address: "1/0/39"
      state_address: "1/0/39"
    - name: "主卫灯带灯"
      address: "1/0/38"
      state_address: "1/0/38"
    - name: "主卧筒灯"
      address: "1/0/35"
      state_address: "1/0/35"
    - name: "主卧灯带灯"
      address: "1/0/36"
      state_address: "1/0/36"
    - name: "主卧主灯"
      address: "1/0/37"
      state_address: "1/0/37"
    - name: "客厅主灯"
      address: "1/0/21"
      state_address: "1/0/21"
    - name: "客厅灯带灯"
      address: "1/0/19"
      state_address: "1/0/19"
    - name: "客厅筒灯"
      address: "1/0/20"
      state_address: "1/0/20"
    - name: "餐厅主灯"
      address: "1/0/23"
      state_address: "1/0/23"
    - name: "餐厅筒灯"
      address: "1/0/22"
      state_address: "1/0/22"
    - name: "玄关灯带"
      address: "1/0/18"
      state_address: "1/0/18"
    - name: "玄关筒灯"
      address: "1/0/17"
      state_address: "1/0/17"
    - name: "次卧筒灯"
      address: "1/0/33"
      state_address: "1/0/33"
    - name: "次卧灯带灯"
      address: "1/0/34"
      state_address: "1/0/34"
    - name: "次卧主灯"
      address: "1/0/24"
      state_address: "1/0/24"

fan:
    - name: "新风风速"
      address: "14/1/3"
      state_address: "14/1/3"
      max_step: 3

switch:
    - name: "新风开关"
      address: "14/1/1"
      state_address: "14/1/1"

# 传感器的数据来源于新风
sensor:
    - name: "湿度"
      state_address: "6/6/81"
      type: 2byte_float
      sync_state: every 180
    - name: "温度"
      state_address: "6/5/81"
      type: 2byte_float
      sync_state: every 180
    - name: "TVOC"
      state_address: "6/3/81"
      type: 2byte_float
      sync_state: every 180
    - name: "二氧化碳"
      state_address: "6/2/81"
      type: 2byte_float
      sync_state: every 180
    - name: "PM2.5"
      state_address: "6/1/81"
      type: 2byte_float
      sync_state: every 180

button:
    - name: "打开次卧布帘"
      address: "2/0/69"
      payload_length: 1
      payload: 1
    - name: "关闭次卧布帘"
      address: "2/0/69"
      payload_length: 1
      payload: 2
    - name: "停止次卧布帘"
      address: "2/0/69"
      payload_length: 1
      payload: 0
    - name: "打开次卧纱帘"
      address: "2/0/70"
      payload_length: 1
      payload: 1
    - name: "关闭次卧纱帘"
      address: "2/0/70"
      payload_length: 1
      payload: 2
    - name: "停止次卧纱帘"
      address: "2/0/70"
      payload_length: 1
      payload: 0
    - name: "打开主卧布帘"
      address: "2/0/68"
      payload_length: 1
      payload: 1
    - name: "关闭主卧布帘"
      address: "2/0/68"
      payload_length: 1
      payload: 2
    - name: "停止主卧布帘"
      address: "2/0/68"
      payload_length: 1
      payload: 0
    - name: "打开主卧纱帘"
      address: "2/0/67"
      payload_length: 1
      payload: 1
    - name: "关闭主卧纱帘"
      address: "2/0/67"
      payload_length: 1
      payload: 2
    - name: "停止主卧纱帘"
      address: "2/0/67"
      payload_length: 1
      payload: 0
    - name: "打开客厅纱帘"
      address: "2/0/66"
      payload_length: 1
      payload: 1
    - name: "关闭客厅纱帘"
      address: "2/0/66"
      payload_length: 1
      payload: 2
    - name: "停止客厅纱帘"
      address: "2/0/66"
      payload_length: 1
      payload: 0
    - name: "回家模式"
      address: "0/0/17"
      payload_length: 1
      payload: 1
    - name: "离家模式"
      address: "0/0/17"
      payload_length: 1
      payload: 2
    - name: "主卧明亮"
      address: "0/0/18"
      payload_length: 1
      payload: 1
    - name: "主卧关灯"
      address: "0/0/18"
      payload_length: 1
      payload: 2

climate:
    - name: "主卧空调"
      temperature_address: "12/5/131"
      target_temperature_address: "12/4/3"
      target_temperature_state_address: "12/4/131"
      on_off_address: "12/1/3"
      on_off_state_address: "12/1/131"
      controller_mode_address: "12/2/3"
      controller_mode_state_address: "12/2/131"
      fan_speed_address: "12/3/3"
      fan_speed_state_address: "12/3/131"
      fan_max_step: 5
      fan_speed_mode: "step"
      fan_zero_mode: "auto"
      temperature_step: 1.0
      controller_modes:
        - "off"
        - "auto"
        - "heat"
        - "cool"
    - name: "儿童房空调"
      temperature_address: "12/5/133"
      target_temperature_address: "12/4/5"
      target_temperature_state_address: "12/4/133"
      on_off_address: "12/1/5"
      on_off_state_address: "12/1/133"
      controller_mode_address: "12/2/5"
      controller_mode_state_address: "12/2/133"
      fan_speed_address: "12/3/5"
      fan_speed_state_address: "12/3/133"
      fan_max_step: 5
      fan_speed_mode: "step"
      fan_zero_mode: "auto"
      temperature_step: 1.0
      controller_modes:
        - "off"
        - "auto"
        - "heat"
        - "cool"
    - name: "书房空调"
      temperature_address: "12/5/134"
      target_temperature_address: "12/4/6"
      target_temperature_state_address: "12/4/134"
      on_off_address: "12/1/6"
      on_off_state_address: "12/1/134"
      controller_mode_address: "12/2/6"
      controller_mode_state_address: "12/2/134"
      fan_speed_address: "12/3/6"
      fan_speed_state_address: "12/3/134"
      fan_max_step: 5
      fan_speed_mode: "step"
      fan_zero_mode: "auto"
      temperature_step: 1.0
      controller_modes:
        - "off"
        - "auto"
        - "heat"
        - "cool"
    - name: "餐厅空调"
      temperature_address: "12/5/130"
      target_temperature_address: "12/4/2"
      target_temperature_state_address: "12/4/130"
      on_off_address: "12/1/2"
      on_off_state_address: "12/1/130"
      controller_mode_address: "12/2/2"
      controller_mode_state_address: "12/2/130"
      fan_speed_address: "12/3/2"
      fan_speed_state_address: "12/3/130"
      fan_max_step: 5
      fan_speed_mode: "step"
      fan_zero_mode: "auto"
      temperature_step: 1.0
      controller_modes:
        - "off"
        - "auto"
        - "heat"
        - "cool"
    - name: "客厅空调"
      temperature_address: "12/5/129"
      target_temperature_address: "12/4/1"
      target_temperature_state_address: "12/4/129"
      on_off_address: "12/1/1"
      on_off_state_address: "12/1/129"
      controller_mode_address: "12/2/1"
      controller_mode_state_address: "12/2/129"
      fan_speed_address: "12/3/1"
      fan_speed_state_address: "12/3/129"
      fan_max_step: 5
      fan_speed_mode: "step"
      fan_zero_mode: "auto"
      temperature_step: 1.0
      controller_modes:
        - "off"
        - "auto"
        - "heat"
        - "cool"
    - name: "次卧空调"
      temperature_address: "12/5/132"
      target_temperature_address: "12/4/4"
      target_temperature_state_address: "12/4/132"
      on_off_address: "12/1/4"
      on_off_state_address: "12/1/132"
      controller_mode_address: "12/2/4"
      controller_mode_state_address: "12/2/132"
      fan_speed_address: "12/3/4"
      fan_speed_state_address: "12/3/132"
      fan_max_step: 5
      fan_speed_mode: "step"
      fan_zero_mode: "auto"
      temperature_step: 1.0
      controller_modes:
        - "off"
        - "auto"
        - "heat"
        - "cool"
